### ISSUE TITLE
Hedera paints in editor when orbiting with alt-click

### ISSUE THREAD

**Issue by vincentaber** [radiatoryang/hedera#12]
It's all in the title, can't orbit in editor while painting because Hedera takes the input as any left click. Pretty awesome apart from that.
Unity 2019.4 LTS

**Comment by radiatoryang** [comment]
sorry just saw this... I think the fix should be straightforward

but in the meantime, for anyone who sees this, the workaround:
- disable ivy painting when orbiting
- or don't orbit, and use right-click navigation instead (which is why I didn't catch this bug)

**Comment by radiatoryang** [comment]
this will be fixed in next release, v1.2.3 ... thanks for filing an issue!
