### ISSUE TITLE
Incorrect leaf placement on concave meshes (with solution discussed)

### ISSUE THREAD

**Issue by alexjhetherington** [radiatoryang/hedera#13]
First, thanks for this tool! It's incredible.

I am building a blocky environment out of mesh colliders. Painting Ivy works correctly, but ivy that grows around corners (say across a roof then down a wall) fails to respect the new surface and does not calculate the new adhesion normal.

It results in unrealistic looking growth, and leaves that only respect the initially painted normal.

![leaf_flat](https://user-images.githubusercontent.com/36995359/108838582-bf1b9980-75cb-11eb-888e-c0d96cfc4f3b.JPG)

It's because of the "find closest point on a mesh collider" logic. It is looking at vertices, and in my case the nearest vertex is very far away (big blocks!).

I have coded a dirty solution for my case : to find the closest point on a mesh collider I send many ray casts outwards from the start point in a rough sphere.

It seems to fix the issue! But obviously it's even slower (by how much I'm not sure).

If you want me to make a PR with my dirty solution let me know :)

![leaf_angle](https://user-images.githubusercontent.com/36995359/108838580-be830300-75cb-11eb-9734-a9cb2d84b12e.JPG)

**Comment by radiatoryang** [comment]
hmm yes, clearly this expensive calculation might be worthwhile sometimes?

I think I'd add this feature as "high detail mesh collider painting" checkbox or something in the inspector?

feel free to submit a PR and I can build off of that to handle the editor UI stuff... thanks!

**Comment by Thundros** [comment]
@alexjhetherington Please submit the PR.

**Comment by radiatoryang** [comment]
this is now integrated and will be part of the next release, v1.2.3 ... thanks for the PR!

![image](https://user-images.githubusercontent.com/2285943/145667999-ecdc7b99-4c0b-4fe1-bf9e-2efee8e42b46.png)
