### ISSUE TITLE
On Runtime?

### ISSUE THREAD

**Issue by furkanyldz06** [radiatoryang/hedera#15]
hi mate hedera great job. congratulations. Is there a way to do this in the runtime and not the editor?

**Comment by radiatoryang** [comment]
It's probably technically possible, but using it at runtime would mean you're distributing the code, which means **you'd have to open source all your project code under GPL as well.** See the License for details. 

Personally, I have no plans to do this. But you're welcome to fork (and also license that fork under GPL and make it open source) and try to figure it out.
