### ISSUE TITLE
Issue with Vines

### ISSUE THREAD

**Issue by Thundros** [radiatoryang/hedera#16]
Hi @radiatoryang ! First off, I'd like to say : HATS OFF TO YOU! This is a work of ART! KUDOS to you my brother! PLEASE keep working on this BEAUTIFUL work of art! <3 Second, I'm having a hard time understanding some of the functions being used in some of the code. I am studying the code in order to learn procedural generation of plants & I think that some of these functions may rely on the use of a DLL file. I would like to ask if you could possibly make this DLL-free. In other words, I would like to ask if you could possibly put the Source code of the DLL into Unity CS form. Or if there's some way you could make it an Open DLL? Either way. Anyway, once again, KUDOS to you, my friend & keep on keeping on with this project! It's BEAUTIFUL! <3

Sincerely, 

Thundros

**Comment by radiatoryang** [comment]
@Thundros sorry, I don't understand your post. I don't see any .DLLs in this repo / package. Can you be more specific please?

**Comment by Thundros** [comment]
@radiatoryang I apologize. I actually had a different question for you. This question was supposed to be posted to a project called "Hey Area Object Spawner", I guess I got that mixed up., Anyway, my question for YOU is actually more of a statement / question. So I added some vines to my 3d pillar object which has physics that make it fall down. Problem is, the vines are not falling WITH the object they are attached to, they stay positioned where they were grown. How can I do that? Once again, I apologize for the confusion. I was tired when I wrote that post & this post as well. :)

**Comment by JacobDSiler** [comment]
> @radiatoryang I apologize. I actually had a different question for you. This question was supposed to be posted to a project called "Hey Area Object Spawner", I guess I got that mixed up., Anyway, my question for YOU is actually more of a statement / question. So I added some vines to my 3d pillar object which has physics that make it fall down. Problem is, the vines are not falling WITH the object they are attached to, they stay positioned where they were grown. How can I do that? Once again, I apologize for the confusion. I was tired when I wrote that post & this post as well. :)

Are the vines set as children of the pillar Game Object? My limited experience would suggest making them children of the pillar Game Object so its transform is then applied to them as well.

**Comment by Thundros** [comment]
Um, @JacobDSiler After you create the vine, the vines are automatically children... O.o

**Comment by JacobDSiler** [comment]
Haha. My mistake. I need to load up a project and recreate your scenario so I can try some things out.

**Comment by radiatoryang** [comment]
Another possibility is that the ivy + meshes have been marked static, which means they won't move or rotate. Make sure they're not static.

But really, I recommend exporting the ivy to .OBJ, and then parenting that .OBJ to the 3D pillar, especially if it's a prefab. That way you can take advantage of GPU instancing, etc. too. And if you export to .OBJ, you bypass Hedera completely and just treat the ivy like any other regular 3D mesh.

(I'm going to close this issue, feel free to open a new issue if you have a specific suggestion or request)

**Comment by Thundros** [comment]
@radiatoryang : yes, but the whole point is to be able to have HEDERA have the ivy follow the actual mesh ( in this case, a falling pillar )
