### ISSUE TITLE
error CS0120: An object reference is required for the non-static field, method, or property 'SceneView.drawGizmos'

### ISSUE THREAD

**Issue by albrrt** [radiatoryang/hedera#9]
Hello, I imported the unity package from Releases into my Unity project (2019.4.8f1). It warned me about obsolete APIs, then I got the following error:
`
Hedera\Editor\Scripts\IvyEditor.cs(282,18): error CS0120: An object reference is required for the non-static field, method, or property 'SceneView.drawGizmos'`

Then underneath it:

`Some scripts have compilation errors which may prevent obsolete API usages to get updated. Obsolete API updating will continue automatically after these errors get fixed.`

Do you know how to fix this?

Thank you!

**Comment by radiatoryang** [comment]
oops, that should read `SceneView.lastActiveSceneView.drawGizmos` ... thanks for the bug report, will push some fixes

**Comment by radiatoryang** [comment]
this should now be fixed in v1.2 release, thanks
